/* date = February 23rd 2022 2:22 pm */

#ifndef HARDCODED_VALUES_H
#define HARDCODED_VALUES_H

#define MAX_FFT_ORDER 10
#define MAX_FFT_SIZE (2<<MAX_FFT_ORDER)


#define TOTAL_WIDTH 200.0F
#define TITLE_HEIGHT 40.0F
#define FIELD_HEIGHT 30.0F
#define FIELD_TITLE_HEIGHT 25.0F
//#define OUTER_MARGIN 10.0F
#define FIELD_MARGIN 5.0F
#define CURSOR_SIZE 10.0F
#define MIN_MAX_LABEL_WIDTH 40.0F

#define DEFAULT_FONT_FILENAME "JetBrainsMono-Regular.ttf"


#define IR_BUFFER_LENGTH 512
#define IR_PIXEL_LENGTH 512

#define ATLAS_MAX_VERTEX_COUNT 4096

#define RING_BUFFER_SLOT_COUNT 4096

#define SLIDER_WIDTH 5.0f
#endif //HARDCODED_VALUES_H

