/* date = February 23rd 2022 2:22 pm */

#ifndef HARDCODED_VALUES_H
#define HARDCODED_VALUES_H

#define APPLICATION_ARENA_SIZE (1024*1024)
#define GUI_IR_ARENA_SIZE (6*1024*1024)
#define MAX_FFT_ORDER 16
#define MAX_FFT_SIZE (2<<MAX_FFT_ORDER)

#define INITIAL_WINDOW_WIDTH 800.0f
#define INITIAL_WINDOW_HEIGHT 600.0f

#define TITLE_HEIGHT 50.0F
#define PARAMETER_PANEL_WIDTH 250.0f

#define FIELD_TITLE_HEIGHT 25.0F
#define FIELD_LOWER_MACHIN_HEIGHT 30.0F
#define FIELD_TOTAL_HEIGHT (FIELD_TITLE_HEIGHT  + FIELD_LOWER_MACHIN_HEIGHT)
#define FIELD_MARGIN 10.0f

#define CURSOR_SIZE 10.0F
#define MIN_MAX_LABEL_WIDTH 40.0F

#define DEFAULT_FONT_FILENAME "JetBrainsMono-Regular.ttf"


#define IR_MAX_PIXEL_WIDTH 4000
#define IR_BUFFER_LENGTH (1024*2)

#define ATLAS_MAX_VERTEX_COUNT (4096)

#define RING_BUFFER_SLOT_COUNT 256

#define SLIDER_WIDTH 40.0f
#endif //HARDCODED_VALUES_H

